"""Initial migration

Revision ID: 1f7f94741f67
Revises: 
Create Date: 2025-06-21 18:55:40.816866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f7f94741f67'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Suppression des drop_index et drop_table inutiles sur une base neuve
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strava_activities',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('athlete_id', sa.BIGINT(), nullable=True),
    sa.Column('activity_id', sa.BIGINT(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('type', sa.VARCHAR(), nullable=True),
    sa.Column('start_date', sa.DATETIME(), nullable=True),
    sa.Column('distance', sa.FLOAT(), nullable=True),
    sa.Column('moving_time', sa.INTEGER(), nullable=True),
    sa.Column('elapsed_time', sa.INTEGER(), nullable=True),
    sa.Column('total_elevation_gain', sa.FLOAT(), nullable=True),
    sa.Column('average_speed', sa.FLOAT(), nullable=True),
    sa.Column('max_speed', sa.FLOAT(), nullable=True),
    sa.Column('average_heartrate', sa.FLOAT(), nullable=True),
    sa.Column('max_heartrate', sa.FLOAT(), nullable=True),
    sa.Column('calories', sa.FLOAT(), nullable=True),
    sa.Column('segments', sa.TEXT(), nullable=True),
    sa.Column('best_efforts', sa.TEXT(), nullable=True),
    sa.Column('elevation_data', sa.TEXT(), nullable=True),
    sa.Column('pace_data', sa.TEXT(), nullable=True),
    sa.Column('heartrate_data', sa.TEXT(), nullable=True),
    sa.Column('power_data', sa.TEXT(), nullable=True),
    sa.Column('weighted_average_watts', sa.FLOAT(), nullable=True),
    sa.Column('max_watts', sa.FLOAT(), nullable=True),
    sa.Column('kilojoules', sa.FLOAT(), nullable=True),
    sa.Column('device_watts', sa.BOOLEAN(), nullable=True),
    sa.Column('suffer_score', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strava_activities_id'), 'strava_activities', ['id'], unique=False)
    op.create_index(op.f('ix_strava_activities_athlete_id'), 'strava_activities', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_strava_activities_activity_id'), 'strava_activities', ['activity_id'], unique=1)
    # ### end Alembic commands ###
