"""add_heart_rate_zones_and_effort_score

Revision ID: 64ceb28582dd
Revises: 832a97690f06
Create Date: 2025-06-26 22:00:02.880600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64ceb28582dd'
down_revision: Union[str, Sequence[str], None] = '832a97690f06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strava_activities', sa.Column('zone_1_time', sa.Float(), nullable=True))
    op.add_column('strava_activities', sa.Column('zone_2_time', sa.Float(), nullable=True))
    op.add_column('strava_activities', sa.Column('zone_3_time', sa.Float(), nullable=True))
    op.add_column('strava_activities', sa.Column('zone_4_time', sa.Float(), nullable=True))
    op.add_column('strava_activities', sa.Column('zone_5_time', sa.Float(), nullable=True))
    op.add_column('strava_activities', sa.Column('below_zone_1_time', sa.Float(), nullable=True))
    op.add_column('strava_activities', sa.Column('above_zone_5_time', sa.Float(), nullable=True))
    op.add_column('strava_activities', sa.Column('effort_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strava_activities', 'effort_score')
    op.drop_column('strava_activities', 'above_zone_5_time')
    op.drop_column('strava_activities', 'below_zone_1_time')
    op.drop_column('strava_activities', 'zone_5_time')
    op.drop_column('strava_activities', 'zone_4_time')
    op.drop_column('strava_activities', 'zone_3_time')
    op.drop_column('strava_activities', 'zone_2_time')
    op.drop_column('strava_activities', 'zone_1_time')
    # ### end Alembic commands ###
