"""add_user_id_to_strava_tokens_and_activities

Revision ID: 832a97690f06
Revises: 1f7f94741f67
Create Date: 2025-06-23 22:39:53.569346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '832a97690f06'
down_revision: Union[str, Sequence[str], None] = '1f7f94741f67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('google_id', sa.String(), nullable=True),
    sa.Column('apple_id', sa.String(), nullable=True),
    sa.Column('firstname', sa.String(), nullable=False),
    sa.Column('lastname', sa.String(), nullable=False),
    sa.Column('charte_accepted', sa.Boolean(), nullable=False),
    sa.Column('charte_accepted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apple_id'),
    sa.UniqueConstraint('google_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('strava_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.BigInteger(), nullable=True),
    sa.Column('activity_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('moving_time', sa.Integer(), nullable=True),
    sa.Column('elapsed_time', sa.Integer(), nullable=True),
    sa.Column('total_elevation_gain', sa.Float(), nullable=True),
    sa.Column('average_speed', sa.Float(), nullable=True),
    sa.Column('max_speed', sa.Float(), nullable=True),
    sa.Column('average_heartrate', sa.Float(), nullable=True),
    sa.Column('max_heartrate', sa.Float(), nullable=True),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('segments', sa.Text(), nullable=True),
    sa.Column('best_efforts', sa.Text(), nullable=True),
    sa.Column('elevation_data', sa.Text(), nullable=True),
    sa.Column('pace_data', sa.Text(), nullable=True),
    sa.Column('heartrate_data', sa.Text(), nullable=True),
    sa.Column('power_data', sa.Text(), nullable=True),
    sa.Column('weighted_average_watts', sa.Float(), nullable=True),
    sa.Column('max_watts', sa.Float(), nullable=True),
    sa.Column('kilojoules', sa.Float(), nullable=True),
    sa.Column('device_watts', sa.Boolean(), nullable=True),
    sa.Column('suffer_score', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strava_activities_activity_id'), 'strava_activities', ['activity_id'], unique=True)
    op.create_index(op.f('ix_strava_activities_athlete_id'), 'strava_activities', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_strava_activities_id'), 'strava_activities', ['id'], unique=False)
    op.create_table('strava_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.BigInteger(), nullable=True),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strava_tokens_athlete_id'), 'strava_tokens', ['athlete_id'], unique=True)
    op.create_index(op.f('ix_strava_tokens_id'), 'strava_tokens', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strava_tokens_id'), table_name='strava_tokens')
    op.drop_index(op.f('ix_strava_tokens_athlete_id'), table_name='strava_tokens')
    op.drop_table('strava_tokens')
    op.drop_index(op.f('ix_strava_activities_id'), table_name='strava_activities')
    op.drop_index(op.f('ix_strava_activities_athlete_id'), table_name='strava_activities')
    op.drop_index(op.f('ix_strava_activities_activity_id'), table_name='strava_activities')
    op.drop_table('strava_activities')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
