"""add_newsletter_subscribers_table

Revision ID: 9ec89eb8d966
Revises: 64ceb28582dd
Create Date: 2025-07-12 17:21:13.210422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ec89eb8d966'
down_revision: Union[str, Sequence[str], None] = '64ceb28582dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
